export const HANDLE_PARSE_SIMILAR_COMPANY_DATA = 'HANDLE_PARSE_SIMILAR_COMPANY_DATA';
export const HANDLE_PARSE_SIMILAR_COMPANY = 'HANDLE_PARSE_SIMILAR_COMPANY';
export const HANDLE_PARSE_SEARCH_COMPANY = 'HANDLE_PARSE_SEARCH_COMPANY';
export const HANDLE_PARSE_COMPANY = 'HANDLE_PARSE_COMPANY';
export const HANDLE_SELECT_DATA = 'HANDLE_SELECT_DATA';
export const HANDLE_FORM_DATA = 'HANDLE_FORM_DATA';

export const FETCH_PARSE_COMPANY = 'FETCH_PARSE_COMPANY';

export const START_PARSE_SIMILAR_COMPANY = 'START_PARSE_SIMILAR_COMPANY';
export const START_PARSE_SEARCH_COMPANY = 'START_PARSE_SEARCH_COMPANY';

export const CLEAR_SIMILAR_COMPANIES_DATA = 'CLEAR_SIMILAR_COMPANIES_DATA';
export const CLEAR_STATE_DATA = 'CLEAR_STATE_DATA';
export const CLEAR_INPUT_DATA = 'CLEAR_INPUT_DATA';
export const CLEAR_SEARCH_COMPANIES_DATA = 'CLEAR_SEARCH_COMPANIES_DATA';